FROM node:20-alpine AS development

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --only=production

COPY . .

RUN npm install

FROM node:20-alpine AS build

WORKDIR /usr/src/app

COPY --from=development /usr/src/app .

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start:dev"]