# Usa una imagen base de Node.js. La versión debe coincidir con la que usas localmente.
FROM node:20-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copia el package.json y package-lock.json (o yarn.lock)
# Esto se aprovecha del cache de capas de Docker. Las dependencias solo se reinstalarán si package.json cambia.
COPY package*.json ./

# Instala todas las dependencias (incluyendo las de desarrollo)
RUN npm install

# Copia el resto del código fuente. Esto es útil si en algún momento no usas volúmenes.
COPY . .

# Expone el puerto que usará la aplicación (el default de NestJS es 3000)
EXPOSE 3000

# Comando para iniciar la aplicación en modo de desarrollo (ideal para Docker Compose en desarrollo)
CMD ["npm", "run", "start:dev"]