FROM node:20-alpine AS builder


WORKDIR /usr/src/app


COPY package*.json ./


RUN npm install


COPY . .


RUN npm run build


FROM node:20-alpine


WORKDIR /usr/src/app


RUN addgroup -S appgroup && adduser -S appuser -G appgroup


COPY --from=builder /usr/src/app/node_modules ./node_modules


COPY --from=builder /usr/src/app/dist ./dist


RUN chown -R appuser:appgroup /usr/src/app


USER appuser


EXPOSE 3000


CMD ["node", "dist/main"]